kind: project
metadata:
  name: imageflowcanvas
spec:
  functions:
    - name: fetch-images
      kind: job
      image: mlrun/mlrun
      path: functions/fetch_images.py
      handler: handler
      with_repo: true
      build:
        requirements:
          - pillow
          - requests
    - name: resize
      kind: job
      image: mlrun/mlrun
      path: functions/resize.py
      handler: handler
      with_repo: true
      build:
        requirements:
          - pillow
    - name: triton-infer
      kind: job
      image: mlrun/mlrun
      path: functions/triton_infer.py
      handler: handler
      with_repo: true
      build:
        requirements:
          - pillow
          - requests
    - name: filter
      kind: job
      image: mlrun/mlrun
      path: functions/filter.py
      handler: handler
      with_repo: true
    - name: aggregate
      kind: job
      image: mlrun/mlrun
      path: functions/aggregate.py
      handler: handler
      with_repo: true
      build:
        requirements:
          - pandas
    - name: serving-llm
      kind: serving
      image: mlrun/mlrun
      path: serving/llm_image_flow.py
      handler: init_context
      with_repo: true
      build:
        requirements:
          - pillow
          - requests
          - pandas
  # Workflows are deprecated in favor of Serving
