# gRPC Workflow RBAC Configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-workflow
  namespace: image-processing
  labels:
    app.kubernetes.io/name: imageflow-canvas
    app.kubernetes.io/component: grpc-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grpc-workflow-role
  namespace: image-processing
  labels:
    app.kubernetes.io/name: imageflow-canvas
    app.kubernetes.io/component: grpc-workflow
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grpc-workflow-binding
  namespace: image-processing
  labels:
    app.kubernetes.io/name: imageflow-canvas
    app.kubernetes.io/component: grpc-workflow
subjects:
- kind: ServiceAccount
  name: grpc-workflow
  namespace: image-processing
roleRef:
  kind: Role
  name: grpc-workflow-role
  apiGroup: rbac.authorization.k8s.io
