apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo
data:
  minio: |
    s3:
      endpoint: minio:9000
      insecure: true
      bucket: argo-artifacts
      keyFormat: "artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
      accessKeySecret:
        name: minio-credentials
        key: access-key
      secretKeySecret:
        name: minio-credentials
        key: secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: argo
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==  # minioadmin (base64)
  secret-key: bWluaW9hZG1pbg==  # minioadmin (base64)