# Simple gRPC Pipeline Test Template
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: simple-grpc-test
  namespace: image-processing
spec:
  serviceAccountName: grpc-workflow
  entrypoint: simple-test
  arguments:
    parameters:
    - name: execution-id
      value: "simple-test"
  
  templates:
  - name: simple-test
    http:
      url: "http://grpc-gateway.image-processing.svc.cluster.local:8080/health"
      method: GET
    outputs:
      parameters:
      - name: status
        valueFrom:
          jsonPath: ".status"
